### ISSUE TITLE
no schema supplied

### ISSUE THREAD

**Issue by ghost** [chairchan/Set-Daily-Bing-Background-As-Desktop-Wallpaper-for-windows-and-ubuntu#1]
everything ok but 

Traceback (most recent call last):
  File "file.py", line 55, in <module>
    main()
  File "file.py", line 48, in main
    image = Image.open(StringIO(requests.get(url).content))
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 421, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 359, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 287, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 338, in prepare_url
    "Perhaps you meant http://{0}?".format(url))
requests.exceptions.MissingSchema: Invalid URL u'/az/hprichbg/rb/WarmiaPoland_DE-DE13043416183_1920x1080.jpg': No schema supplied. Perhaps you meant http:///az/hprichbg/rb/WarmiaPoland_DE-DE13043416183_1920x1080.jpg?

i get this error

i tried dconf gsettings and different urls for invalid url but same i cant change for 17.3 xfce mint the right click Desktop Settings the folder for backgrounds everytime i change it to Downloads it drops back to /usr/share etc you probably know

can you help thanks

i have file:///usr/share/backgrounds/warty-final-ubuntu.png set in dcong-editor for the org.gnome uri in the source despite having different folder e.g. maya nadia and so on in this directory i installed via sudo apt-get install mint-backgrounds-* i tried also /home/noname/Downloads/*.jpg or whatever it didnt help

**Comment by lsq27** [comment]
@Selektorenliste 
- **To Solve** '''requests.exceptions.MissingSchema: Invalid URL u'/az/hprichbg/rb/WarmiaPoland_DE-DE13043416183_1920x1080.jpg': No schema supplied. Perhaps you meant http:///az/hprichbg/rb/WarmiaPoland_DE-DE13043416183_1920x1080.jpg?'''
  - change  (**i've fix it in today's Commits**)
    ```python
    url = data['images'][i]['url']
    ```
    to 
    ```
    url = 'http://www.bing.com' + data['images'][i]['url']
    ```
    Via Chinese ip,i get the 'url' with 'http://www.bing.com' from [bing'API](http://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US) ,but today i find bing shorten the 'url' to relative path.
Via American ip,i get the 'url' without 'http://www.bing.com'.
- As for error in 17.3 xfce mint,which i haven't used,i find [this](http://stackoverflow.com/a/21213504) on stackoverflow,maybe it will help you.
- i will make code work in other Linux distributions after i finish my final exam,sorry for my poor English :)
